# Use root/example as user/password credentials
# echo 127.0.0.1 mysql >> /etc/hosts
version: '3.0'

services:
    mysql:
        hostname: mysql
        image: mysql:5.7
        container_name: mysql
        restart: always
        # restart can be removed
        environment:
            MYSQL_DATABASE: 'kindergarten'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: '1'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'p1assword'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - /docker-common-meta-files/mysql/db:/var/lib/mysql:cached
            # please define cache folder for database metadata (to preserve state)

networks:
    default:
        external:
            name: local.net
# network setup in case you need >>
# docker network create local.net